sudo: false

env:
  global:
  - GH_REF: github.com/nomeata/incredible-demo.git
  - secure: "ZMFRlzcJEut3E4nDZpcM+wlkxOzRdTYN9pmlTApoMeYs2PCfaREpLVZCQ8EZ0XjJdKQzhsRZyQsa64/IcFmhFeAiBhaura5pE4VwXd6RKPJwNE9tgnpCJ7G/R0JIFzUA2SFgD4+UW5/Db1JgHIjOTVtvYqtlxjhQOhVTWi7vBlws4EccA+tGZk0VAkHNG4Uk78LZlfXBbluoxjYxI9SeMoPWSlwYUWfkvhl5GqoV18Si9i4vOmT5/T/yb84uQ/bHH3UbrWZ9UF2WtebC9/cvFhWwj1Qa2xyvTYsXfCEKJq6TV0OgialuECByDb5e+cWIixShLpwYTSJV4BrCEMxkLrOoRgLRPJ7LA+I+tjZsh1zmwJqyE5Tlbaq5fX/mE/4Y/HgrXbS4qNGbF6RvzVYhJAxQKFV3LpnrPthFQ5HXfZpyCJt32jTlsfsUdpEUM+QXFqnrDtF7BBEh7AJW2iO/ktObeBNulS428pHL7brA5IBfk/j4WeTAs2l7ZvTy/f8AQbPFv6BPWONJp81E2tdmo1oa+j1I4r4i9hP72Uf97dElZKsF4UANWp8Z7g1OShDymnG1R74gWQFn4utAC33jOF94mcTsHYh3phC/ZOGvdqQGmkZrhF0sVX8fdpxuBFZ6+BgobFiNMJowigM1tleDPTtcvgYbaziFgJ92/NblY54="


addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.22
    - ghc-7.8.4
    - alex-3.1.4
    - happy-1.19.5

cache:
  bundler: false
  directories:
  - $HOME/.ghc/
  - $HOME/.ghcjs/
  - $HOME/.cabal/bin
  - $HOME/.cabal/share
  - $HOME/.cabal/lib

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/cabal/1.22/bin:$PATH
    - export PATH=/opt/alex/3.1.4/bin:$PATH
    - export PATH=/opt/happy/1.19.5/bin:$PATH
    - export PATH=/opt/ghc/7.8.4/bin:$PATH
    - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share

install:
    # install ghcjs
    - cabal-1.22 update
    - cabal-1.22 install Cabal
    - test -e $HOME/.cabal/bin/HsColour || cabal-1.22 install hscolour
    - test -e $HOME/.cabal/bin/ghcjs || git clone https://github.com/ghcjs/ghcjs-prim.git
    - test -e $HOME/.cabal/bin/ghcjs || git clone https://github.com/ghcjs/haddock-internal.git
    - test -e $HOME/.cabal/bin/ghcjs || git clone https://github.com/ghcjs/ghcjs.git
    - test -e $HOME/.cabal/bin/ghcjs || cabal-1.22 install ./ghcjs-prim ./haddock-internal ./ghcjs
    - ghcjs --version
    - ghcjs-boot --version
    - test -e $HOME/.ghcjs/*/ghcjs/ghcjs_boot.completed || ghcjs-boot --dev --no-haddock --no-prof

    # install dependencies
    - make prepare

script:
    - make
    - ( cd logic && cabal-1.22 test --show-details=streaming )
    - make docs

after_success:
    - '[ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_SECURE_ENV_VARS" = "true" ] &&  [ "$TRAVIS_PULL_REQUEST" = "false" ] && ./.travis-push-gh-pages.sh'

before_cache:
  - rm -rf $HOME/.ghcjs/*/ghcjs/ghcjs-boot/
  - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share

